# Generated by Django 2.1.5 on 2019-02-01 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('airplane_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('manufacturer', models.TextField(default='')),
                ('max_seats', models.IntegerField(default=0)),
                ('type', models.TextField(default='')),
            ],
            options={
                'db_table': 'Airplane',
            },
        ),
        migrations.CreateModel(
            name='Airplane_Customer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('airplane_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Airplane')),
            ],
            options={
                'db_table': 'Airplane_Customer',
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('airport_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('airport_name', models.TextField(default='')),
                ('city', models.TextField(default='')),
                ('state', models.TextField(default='')),
            ],
            options={
                'db_table': 'Airport',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cust_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('c_first_name', models.TextField(default='')),
                ('c_last_name', models.TextField(default='')),
                ('address', models.TextField(default='')),
                ('city', models.TextField(default='')),
                ('postal_code', models.TextField(blank=True, null=True)),
                ('email', models.TextField(default='')),
                ('phone', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flight_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('scheduled_dep_time', models.TextField(blank=True, null=True)),
                ('scheduled_arriv_time', models.TextField(blank=True, null=True)),
                ('departure_airportid', models.IntegerField(blank=True, db_column='departure_airportID', null=True)),
                ('arrival_airportid', models.IntegerField(blank=True, db_column='arrival_airportID', null=True)),
            ],
            options={
                'db_table': 'Flight',
            },
        ),
        migrations.CreateModel(
            name='Flight_Airplane',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('airplane_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Airplane')),
                ('flight_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Flight')),
            ],
            options={
                'db_table': 'Flight_Airplane',
            },
        ),
        migrations.CreateModel(
            name='Flight_Airport',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Airport_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Airport')),
                ('flight_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Flight')),
            ],
            options={
                'db_table': 'Flight_Airport',
            },
        ),
        migrations.CreateModel(
            name='Flight_Customer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Customer')),
                ('flight_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Flight')),
            ],
            options={
                'db_table': 'Flight_Customer',
            },
        ),
        migrations.AddField(
            model_name='airplane_customer',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Customer'),
        ),
    ]
