# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-29 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airplane_id', models.IntegerField(blank=True, null=True)),
                ('manufacturer', models.TextField()),
                ('max_seats', models.IntegerField()),
                ('type', models.TextField()),
            ],
            options={
                'db_table': 'Airplane',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AirplaneAirport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_dep_time', models.DateTimeField(blank=True, null=True)),
                ('scheduled_arr_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Airplane_Airport',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AirplaneCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'Airplane_Customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport_id', models.IntegerField(blank=True, null=True)),
                ('airport_name', models.TextField()),
                ('city', models.TextField()),
                ('state', models.TextField()),
            ],
            options={
                'db_table': 'Airport',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_id', models.IntegerField(blank=True, null=True)),
                ('c_first_name', models.TextField()),
                ('c_last_name', models.TextField()),
                ('address', models.TextField()),
                ('city', models.TextField()),
                ('postal_code', models.IntegerField(blank=True, null=True)),
                ('email', models.TextField()),
                ('phone', models.IntegerField()),
            ],
            options={
                'db_table': 'Customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerSeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'Customer_Seat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.TextField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'Seat',
                'managed': False,
            },
        ),
    ]
