# Generated by Django 2.1.5 on 2019-02-01 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Airplane_Customer',
            new_name='Customer_Airplane',
        ),
    ]
