# Generated by Django 2.1.5 on 2019-01-31 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airplane_Customer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Airplane_Customer',
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flight_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('scheduled_dep_time', models.TextField(blank=True, null=True)),
                ('scheduled_arriv_time', models.TextField(blank=True, null=True)),
                ('departure_airportid', models.IntegerField(blank=True, db_column='departure_airportID', null=True)),
                ('arrival_airportid', models.IntegerField(blank=True, db_column='arrival_airportID', null=True)),
            ],
            options={
                'db_table': 'Flight',
            },
        ),
        migrations.AlterModelOptions(
            name='airplane',
            options={},
        ),
        migrations.AlterModelOptions(
            name='airport',
            options={},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
        migrations.AddField(
            model_name='airplane_customer',
            name='airplane_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Airplane'),
        ),
        migrations.AddField(
            model_name='airplane_customer',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Customer'),
        ),
    ]
