# Generated by Django 2.1.5 on 2019-01-30 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airplane',
            options={},
        ),
        migrations.AlterModelOptions(
            name='airplaneairport',
            options={},
        ),
        migrations.AlterModelOptions(
            name='airplanecustomer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='airport',
            options={},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='customerseat',
            options={},
        ),
        migrations.AlterModelOptions(
            name='seat',
            options={},
        ),
    ]
