# Generated by Django 2.1.5 on 2019-01-31 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190131_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight_Airplane',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Flight_Airplane',
            },
        ),
        migrations.CreateModel(
            name='Flight_Airport',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Flight_Airport',
            },
        ),
        migrations.RemoveField(
            model_name='airplane',
            name='id',
        ),
        migrations.RemoveField(
            model_name='airport',
            name='id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='id',
        ),
        migrations.AlterField(
            model_name='airplane',
            name='airplane_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='airplane',
            name='manufacturer',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='airplane',
            name='max_seats',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='airplane',
            name='type',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='airport',
            name='airport_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='airport',
            name='airport_name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='airport',
            name='city',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='airport',
            name='state',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='c_first_name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='c_last_name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cust_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flight_airport',
            name='Airport_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Airport'),
        ),
        migrations.AddField(
            model_name='flight_airport',
            name='flight_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Flight'),
        ),
        migrations.AddField(
            model_name='flight_airplane',
            name='airplane_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Airplane'),
        ),
        migrations.AddField(
            model_name='flight_airplane',
            name='flight_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Flight'),
        ),
    ]
