# Generated by Django 2.1.5 on 2019-02-01 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190201_2246'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer_airplane',
            table='Customer_Airplane',
        ),
    ]
