# Generated by Django 2.1.5 on 2019-02-01 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20190201_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_airplane',
            name='airplane_id',
        ),
        migrations.RemoveField(
            model_name='customer_airplane',
            name='customer_id',
        ),
        migrations.DeleteModel(
            name='Customer_Airplane',
        ),
    ]
