# Generated by Django 2.1.5 on 2019-01-31 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20190131_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight_Customer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Customer')),
                ('flight_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Flight')),
            ],
        ),
    ]
