# Generated by Django 2.1.5 on 2019-02-01 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_flight_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='scheduled_arriv_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='scheduled_dep_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
