# Generated by Django 2.1.5 on 2019-02-01 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20190201_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Airplane',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('airplane_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Airplane')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Customer')),
            ],
            options={
                'db_table': 'Customer_Airplane',
            },
        ),
    ]
