# Generated by Django 2.1.5 on 2019-02-01 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20190201_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='postal_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
