# Generated by Django 2.1.5 on 2019-02-02 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_customer_airplane'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight_airport',
            old_name='Airport_id',
            new_name='airport_id',
        ),
    ]
