# Generated by Django 2.1.5 on 2019-02-02 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20190202_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='cust_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='myapp.Customer'),
        ),
    ]
