# Generated by Django 2.1.5 on 2019-02-03 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_flight_cust_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_airplane',
            old_name='customer_id',
            new_name='cust_id',
        ),
    ]
