# Generated by Django 2.1.5 on 2019-02-01 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20190201_0308'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='flight_customer',
            table='Flight_Customer',
        ),
    ]
