# Generated by Django 2.1.5 on 2019-02-01 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20190201_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='customer_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='myapp.Customer'),
            preserve_default=False,
        ),
    ]
