# Generated by Django 2.1.5 on 2019-02-03 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20190203_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='arrival_airportid',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='departure_airportid',
        ),
        migrations.AddField(
            model_name='flight',
            name='arrival_airport',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='departure_airport',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='scheduled_arriv_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='scheduled_dep_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
