# Generated by Django 2.1.5 on 2019-02-03 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20190203_2057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight_customer',
            old_name='customer_id',
            new_name='cust_id',
        ),
    ]
