# Generated by Django 2.1.5 on 2019-02-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20190203_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='customer',
            name='c_first_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='customer',
            name='c_last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='customer',
            name='postal_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
