# Generated by Django 2.1.5 on 2019-02-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_flight_airplane_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='scheduled_arriv_time',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='scheduled_dep_time',
            field=models.TextField(blank=True, null=True),
        ),
    ]
