# Generated by Django 2.1.5 on 2019-02-24 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20190224_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='airplane_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Airplane'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='cust_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Customer'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
