# Generated by Django 2.1.5 on 2019-02-24 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20190224_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='airplane_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='cust_id',
            field=models.IntegerField(null=True),
        ),
    ]
