# Generated by Django 2.1.5 on 2019-02-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20190211_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(default='', max_length=30, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='c_last_name',
            field=models.CharField(default='', max_length=30, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(default='', max_length=30, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(default='', max_length=30, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.IntegerField(verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='postal_code',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Postal Code'),
        ),
    ]
