# Generated by Django 2.1.5 on 2019-02-24 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20190211_1632'),
        ('myapp', '0012_auto_20190224_1625'),
    ]

    operations = [
    ]
