# Generated by Django 2.1.5 on 2019-02-13 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_flight_airplane_id'),
        ('myapp', '0015_auto_20190211_1632'),
    ]

    operations = [
    ]
