# Generated by Django 2.1.5 on 2019-02-25 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20190224_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='airplane_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Airplane'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='cust_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Customer'),
        ),
    ]
