# Generated by Django 2.1.5 on 2019-02-25 00:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20190225_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='date_arriv',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='date_dep',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
