# Generated by Django 2.1.5 on 2019-02-24 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_merge_20190224_1721'),
        ('myapp', '0016_merge_20190212_1946'),
    ]

    operations = [
    ]
