# Generated by Django 2.1.5 on 2019-02-25 01:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20190225_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='scheduled_arriv_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flight',
            name='scheduled_dep_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
