# Generated by Django 2.1.5 on 2019-02-25 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_merge_20190224_1837'),
        ('myapp', '0016_auto_20190225_0018'),
    ]

    operations = [
    ]
