# Generated by Django 2.1.5 on 2019-02-25 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_merge_20190224_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='c_first_name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='c_last_name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cust_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='postal_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='scheduled_arriv_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='scheduled_dep_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
