# Generated by Django 2.1.5 on 2019-02-25 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_auto_20190224_2007'),
        ('myapp', '0018_auto_20190225_0102'),
    ]

    operations = [
    ]
