# Generated by Django 2.2 on 2019-04-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_merge_20190224_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cust_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
